POST http://localhost:3000/api/inputs/cloudinary?database=24a2356964104481ac700d0ad77148c0 
{
      "asset_id":"3c0802af579268a817b91d52f340df24",
         "public_id":"e5k8sm3pb9adlmnwu0c9",
            "version":"1623612849",
               "version_id":"0969cc24090a4edc6a4ee2a0de6387d1",
                  "signature":"bd45df701ec04ca626814475c5b369450ed139fe",
                     "width":"500",
                        "height":"173",
                           "format":"webp",
                              "resource_type":"image",
                                 "secure_url":"https://res.cloudinary.com/dhzju0u55/image/upload/v1623612849/e5k8sm3pb9adlmnwu0c9.webp",
                                    "metadata":{
         "metadata_ocr":"You are viewing the realtime logs of the Serverless Functions in your deployment. To filter\n",
               "metadata_url":"http://localhost:3000/__/"
                  }
                  
}
